<%@ Language="JavaScript" %>
<%
/* Auto-generated by G3pix AxonLive Visual Builder */

/**
 * MODAL MANAGEMENT TIPS:
 * - To show a modal:    G3AxonLive.showModal("modalID");
 * - To close a modal:   G3AxonLive.closeModal("modalID");
 * - To toggle a modal:  G3AxonLive.toggleModal("modalID");
 * 
 * You can call these from any client-side onclick handler or via 
 * AxonLive.Trigger("btnID", "onclick") from the server.
 */

var AxonLive = Server.CreateObject("G3AXONLIVE");
AxonLive.InitPage();

var sessionID = Session.SessionID;

// Restore persisted component state (survives across async re-executions)
var axl_fileuploader_1_val = AxonLive.GetComponentProperty(sessionID, "axl_fileuploader_1", "val");
if (axl_fileuploader_1_val === null || axl_fileuploader_1_val === "") { axl_fileuploader_1_val = ""; }

if (AxonLive.IsAsyncRequest) {
    var compID  = AxonLive.EventComponentID;
    var evtName = AxonLive.EventName;

    switch (compID) {
        case "axl_fileuploader_1":
            // Granular API: Auto-generated proxies for interaction
            var axl_fileuploader_1 = AxonLive.GetComponent("axl_fileuploader_1");
            // Multipart File Upload Logic
            if (Request.TotalBytes > 0 && Request.ServerVariables("HTTP_X_G3AL_UPLOAD") == "true") {
                var uploader = Server.CreateObject("G3FILEUPLOADER");
                uploader.MaxFileSize = 5242880;
                uploader.BlockExtension("exe");
                uploader.BlockExtension("bat");
                uploader.PreserveOriginalName = true;
                var result = uploader.Process("file", "/uploads", "");
                if (result.Item("IsSuccess")) { axl_fileuploader_1_val = "Success: " + result.Item("RelativePath"); }
                else { axl_fileuploader_1_val = "Error: " + result.Item("ErrorMessage"); }
            }
            if (AxonLive.GetEventArg("value") !== "") { axl_fileuploader_1_val = AxonLive.GetEventArg("value"); }
            break;

    }

    // Persist updated state for the next async call
    AxonLive.SetComponentProperty(sessionID, "axl_fileuploader_1", "val", String(axl_fileuploader_1_val));


    AxonLive.RegisterComponent("axl_fileuploader_1", '<div id="axl_fileuploader_1" style="width:300px;height:80px;position:absolute;top:10px;left:10px;"><div class="sidebar-header" style="font-size:10px; margin-bottom:5px;">File Upload</div><input type="file" id="axl_fileuploader_1_file" onchange="G3AxonLive.uploadFile(&quot;axl_fileuploader_1&quot;, &quot;axl_fileuploader_1_file&quot;, &quot;onupload&quot;)"><div style="font-size:10px; color:#666; margin-top:5px;">Result: '+(axl_fileuploader_1_val || "Ready")+'</div></div>');

    AxonLive.EndAsyncResponse();
}
%>
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AxonLive Application</title>
        <link rel="stylesheet" href="/css/axonasp.css">

    </head>

    <body>

        <div id="main-container">
            <div id="content">
                <div id="axl_fileuploader_1" style="width:300px;height:80px;position:absolute;top:10px;left:10px;">
                    <div class="sidebar-header" style="font-size:10px; margin-bottom:5px;">File Upload</div>
                    <input type="file" id="axl_fileuploader_1_file"
                        onchange="G3AxonLive.uploadFile('axl_fileuploader_1', 'axl_fileuploader_1_file', 'onupload')">
                    <div id="axl_fileuploader_1_result" style="font-size:10px; color:#666; margin-top:5px;">
                        Result: <%=Server.HTMLEncode(String(axl_fileuploader_1_val || "Ready"))%>
                    </div>
                </div>

            </div>
        </div>



        <script src="/axonlive/g3axonlive.js"></script>
        <script>
            G3AxonLive.init();
        </script>
    </body>

</html>