<%@ Language="JavaScript" %>
<%
/* Auto-generated by G3pix AxonLive Visual Builder */
function renderCounter(currentValue) {
    return '<span id="lblCounter">Counter: ' + currentValue + '</span>';
}

var AxonLive = Server.CreateObject("G3AXONLIVE");
AxonLive.InitPage();

var sessionID = Session.SessionID;
var _raw_lblCounter_val = AxonLive.GetComponentProperty(sessionID, "lblCounter", "val");
var lblCounter_val = 0;
if (_raw_lblCounter_val !== "" && _raw_lblCounter_val !== null && !isNaN(parseInt(_raw_lblCounter_val, 10))) {
    lblCounter_val = parseInt(_raw_lblCounter_val, 10);
}

if (AxonLive.IsAsyncRequest) {
    var compID  = AxonLive.EventComponentID;
    var evtName = AxonLive.EventName;

    switch (compID) {
        case "axl_button_3":
            if (evtName === "onclick") {
                lblCounter_val = lblCounter_val + 1;
            }
            break;
    }

    AxonLive.SetComponentProperty(sessionID, "lblCounter", "val", String(lblCounter_val));
    AxonLive.RegisterComponent("lblCounter", renderCounter(lblCounter_val));
    AxonLive.EndAsyncResponse();
}
%>
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AxonLive Application</title>
        <link rel="stylesheet" href="/css/axonasp.css">
    </head>

    <body>

        <div id="main-container">
            <div id="content">
                <%
                Response.Write(renderCounter(lblCounter_val));
                %>
                <button id="axl_button_3" class="btn btn-primary" data-g3al-id="axl_button_3" data-g3al-event="click"
                    data-g3al-event-name="onclick">Click Me</button>

            </div>
        </div>
        <script src="/axonlive/g3axonlive.js"></script>
        <script>
            G3AxonLive.init();
        </script>
    </body>

</html>