<%@ Language="JavaScript" %>
<%
/* Auto-generated by G3pix AxonLive Visual Builder */
function toBool(rawValue, defaultValue) {
    if (rawValue === null || rawValue === undefined || rawValue === '') {
        return defaultValue;
    }

    rawValue = String(rawValue).toLowerCase();
    return rawValue === 'true' || rawValue === '1';
}

function renderToggleLink(isVisible) {
    var label = isVisible ? 'Hide Alert' : 'Show Alert';
    return '<a href="#" id="axl_link_2" data-g3al-id="axl_link_2" data-g3al-event="click" data-g3al-event-name="onclick">' + label + '</a>';
}

function renderModal(isVisible) {
    var displayStyle = isVisible ? 'block' : 'none';

    return '' +
        '<div id="axl_modal_3" class="window" style="display:' + displayStyle + ';">' +
            '<div class="window-header">' +
                '<span>Notice</span>' +
                '<span style="cursor:pointer" onclick="G3AxonLive.trigger(\'axl_link_2\', \'onclick\'); return false;">X</span>' +
            '</div>' +
            '<div class="window-body">' +
                '<div class="alert alert-success">This is an alert.</div>' +
                '<div style="margin-top: 15px; display:flex; justify-content:flex-end; gap:5px;">' +
                    '<button class="btn btn-primary" onclick="G3AxonLive.trigger(\'axl_link_2\', \'onclick\'); return false;">OK</button>' +
                '</div>' +
            '</div>' +
        '</div>';
}

var AxonLive = Server.CreateObject("G3AXONLIVE");
AxonLive.InitPage();

var sessionID = Session.SessionID;
var modalVisible = toBool(AxonLive.GetComponentProperty(sessionID, 'axl_modal_3', 'visible'), true);

if (AxonLive.IsAsyncRequest) {
    var compID  = AxonLive.EventComponentID;
    var evtName = AxonLive.EventName;

    switch (compID) {
        case "axl_link_2":
            if (evtName === "onclick") {
                modalVisible = !modalVisible;
            }
            break;
    }

    AxonLive.SetComponentProperty(sessionID, 'axl_modal_3', 'visible', modalVisible ? 'true' : 'false');
    AxonLive.RegisterComponent("axl_link_2", renderToggleLink(modalVisible));
    AxonLive.RegisterComponent("axl_modal_3", renderModal(modalVisible));
    AxonLive.EndAsyncResponse();
}
%>
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AxonLive Application</title>
        <link rel="stylesheet" href="/css/axonasp.css">
    </head>

    <body>

        <div id="main-container">
            <div id="content">
                <div>Raw HTML</div>
                <%
                Response.Write(renderToggleLink(modalVisible));
                Response.Write(renderModal(modalVisible));
                %>
            </div>
        </div>
        <script src="/axonlive/g3axonlive.js"></script>
        <script>
            G3AxonLive.init();
        </script>
    </body>

</html>